import pytest
from h_prime_store import PrimeStore

# NOTE: PrimeStore._primes is a *class* variable shared across all instances
# and across tests within this session. Tests that rely on the exact value of
# len(PrimeStore) should account for primes already generated by earlier tests.


# ---------------------------------------------------------------------------
# __getitem__ — integer index
# ---------------------------------------------------------------------------


def test_getitem_zeroth_prime_is_2():
    pass


@pytest.mark.parametrize(
    "i, expected",
    [
        (0, 2),
        (1, 3),
        (2, 5),
        (3, 7),
        (4, 11),
    ],
)
def test_getitem_known_primes_by_index(i, expected):
    pass


def test_getitem_triggers_generation_beyond_cache():
    pass


def test_getitem_negative_index_raises_index_error():
    pass


@pytest.mark.parametrize("bad_key", [1.5, "2", None, [0]])
def test_getitem_non_int_non_slice_raises_type_error(bad_key):
    pass


# ---------------------------------------------------------------------------
# __getitem__ — slice
# ---------------------------------------------------------------------------


def test_getitem_slice_returns_correct_sublist():
    pass


def test_getitem_slice_negative_start_raises():
    pass


def test_getitem_slice_negative_stop_raises():
    pass


def test_getitem_open_ended_slice_positive_step_raises():
    pass


def test_getitem_open_ended_slice_negative_step_raises():
    pass


# ---------------------------------------------------------------------------
# __iter__
# ---------------------------------------------------------------------------


def test_iter_yields_primes_in_order():
    pass


def test_iter_is_infinite_until_break():
    pass


def test_two_independent_iterators_start_from_2():
    pass


def test_second_iteration_starts_fresh():
    pass


# ---------------------------------------------------------------------------
# __len__
# ---------------------------------------------------------------------------


def test_len_increases_after_generating_new_primes():
    pass


def test_len_returns_int():
    pass


# ---------------------------------------------------------------------------
# Shared class variable
# ---------------------------------------------------------------------------


def test_two_instances_share_same_primes_list():
    pass
